# Generated by Django 4.1.7 on 2023-03-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0002_listitem_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
